name: Sequential-Grounding
rng_seed: 42
num_gpu: 1
mode: train
note: ''
base_dir: ''
exp_dir: !!python/object/apply:pathlib.PosixPath
- Sequential-Grounding
- 2025-09-18-11:18:04.032299
resume: false
debug:
  flag: false
  hard_debug: false
  debug_size: 4
logger:
  name: wandb
  entity: TBD
  autoname: true
  run_id: 326gsvnc
data:
  load_scan_options:
    load_inst_info: true
    load_pc_info: true
    load_segment_info: false
    load_image_segment_feat: false
    load_point_segment_feat: false
    load_image_obj_feat: false
    load_voxel_obj_feat: false
  process_num: 0
  scene_verse_base: /home/zijun/hdd1/sg3d/scene_verse_base
  scene_verse_aux: /home/zijun/hdd1/sg3d/scene_verse_aux
  scene_verse_pred: /home/zijun/hdd1/sg3d/scene_verse_pred
  sequential_grounding_base: /home/zijun/hdd1/sg3d/sequential_grounding_base
  multi_step_context: true
  drop_data_percent: 0.0
  train:
  - SequentialGrounding3RScan
  val:
  - SequentialGrounding3RScan
  test:
  - SequentialGrounding3RScan
  SequentialGroundingScanNet:
    pc_type: gt
    evaluator: SequentialGroundingEval
  SequentialGrounding3RScan:
    pc_type: gt
    evaluator: SequentialGroundingEval
  SequentialGroundingMultiScan:
    pc_type: gt
    evaluator: SequentialGroundingEval
  SequentialGroundingARKitScenes:
    pc_type: gt
    evaluator: SequentialGroundingEval
  SequentialGroundingHM3D:
    pc_type: gt
    evaluator: SequentialGroundingEval
task: SequentialGrounding
data_wrapper:
  train: SequentialGroundingDatasetWrapper
  val: SequentialGroundingDatasetWrapper
  test: SequentialGroundingDatasetWrapper
trainer: MultitaskTrainer
ckpt_path: ''
pretrain_ckpt_path: /home/zijun/hdd1/sg3d/sequential_grounding_base/LEO-1_align_lora
dataloader:
  batchsize: 4
  num_workers: 1
  balance_dataset: false
  filter_empty_annotations: false
solver:
  gradient_accumulation_steps: 5
  lr: 0.0001
  grad_norm: 5.0
  optim:
    name: AdamW
    args:
      lr: 0.0001
      betas:
      - 0.9
      - 0.999
      weight_decay: 0.05
  sched:
    name: warmup_cosine
    args:
      warmup_steps: 400
  epochs: 50
  epochs_per_eval: 10
  epochs_per_save: 0
eval:
  save: false
  predict_mode: false
model:
  name: SequentialGrounder
  notes: try
  pre_grounding: true
  llm:
    name: Vicuna7B
    cfg_path: /home/zijun/hdd1/sg3d/vicuna-7b
    truncation_side: right
    max_context_len: 256
    max_out_len: 256
    lora:
      flag: true
      rank: 16
      alpha: 16
      target_modules:
      - q_proj
      - k_proj
      - v_proj
      - o_proj
      - gate_proj
      - up_proj
      - down_proj
      dropout: 0.0
  vision2d:
    name: GridFeatureExtractor2D
    backbone_name: convnext_base
    backbone_pretrain_dataset: laion2b
    use_pretrain: true
    pooling: avg
    freeze: true
  vision3d:
    name: OSE3D
    hidden_dim: 256
    use_spatial_attn: true
    use_embodied_token: false
    fourier_size: 84
    lr: 0.0001
    spatial_encoder:
      dim_loc: 6
      num_attention_heads: 8
      dim_feedforward: 2048
      dropout: 0.1
      activation: gelu
      spatial_multihead: true
      spatial_dim: 5
      spatial_dist_norm: true
      spatial_attn_fusion: cond
      num_layers: 3
      obj_loc_encoding: same_all
      pairwise_rel_type: center
    backbone:
      net:
        _target_: modules.layers.pointnet.PointNetPP
        sa_n_points:
        - 32
        - 16
        - null
        sa_n_samples:
        - 32
        - 32
        - null
        sa_radii:
        - 0.2
        - 0.4
        - null
        sa_mlps:
        - - 3
          - 64
          - 64
          - 128
        - - 128
          - 128
          - 128
          - 256
        - - 256
          - 256
          - 512
          - 768
      path: /home/zijun/hdd1/sg3d/sequential_grounding_base/pointnet/pointnet.pth
      freeze: true
  clip_txt_guidance:
    flag: false
    clip_out_dim: 1024
  ground_head:
    name: SequentialGroundHead
    args:
      hidden_size: 4096
      num_attention_heads: 32
      num_layers: 2
    lr: 0.0001
  loss_list:
  - LLMLoss
  - SequentialGroundLoss
  - obj_cls_post_loss
  vis_loss_list: []
  loss_weights:
    SequentialGroundLoss: 1
